
server:
  port: 8081

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://3.1.27.251:3306/medical_system?useUnicode=true & characterEncoding=utf-8 &
      useSSL=false & serverTimezone=Asia/Shanghai
    username: admin
    password: 111111

mybatis:
 mapper-locations: classpath:/mapper/*.xml
 type-aliases-package: com.example.demo.entity
